### ISSUE TITLE
VelococityRender generating link targets with trailing .html

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#125] opened 2015-02-09 18:29 UTC
The target URL on hyperlinks generated by the Velocity render for result graph items and for the objects of statements appear to be extended with trailing .html (ie. the api:name of the rendering operation). Because they are (or should be) 'thing' references, they should be plain and 'unextended'.
The link text correctly show the un-extended URI. eg.

`<a href="/elda/data/bathing-water-quality/compliance/point/03600/year/1988.html">http://environment.data.gov.uk/data/bathing-water-quality/compliance/point/03600/year/1988</a>`

ie. neither the link text nor the link target should have the trailing .html.

**Comment by ijdickinson** [comment] 2015-02-10 14:44
Isn't this just a duplicate of #106 ?

**Comment by skwlilac** [comment] 2015-02-10 15:44
Yes... i think it is. Apologies. Not sure if it depends on the renderer being the default or not (suspect not).

Happy to close as a dup of #106

**Comment by ijdickinson** [comment] 2015-02-10 15:59
I'm not quite sure what you're expecting to be the correct behaviour here anyway. Suppose the default renderer was `.html` using xslt, and you're viewing a velocity rendered page using `.vhtml`. In that case, would not the correct behavious be to add the `.vhtml` suffix to the URI? Otherwise the first link you traverse will drop you into a different rendering. That was the bug report that lead to the suffix being added in the first place.

**Comment by skwlilac** [comment] 2015-02-10 17:19
There are two categories of URI, those arising from 'data' triples returned from the SPARQL view query and those injected by elda and/or the render for linking pages. In the case of URI in the data, modulo staging rewrites, they should be as present in the data (usually without suffices) - regardless of conneg or &_format or trailing .format.

For elda/renderer generated links for `next`/`prev`/`first` - `sort`, `more-like-this` (&P=V filters) etc. Then the `.ext` should follow the request. If present in the request, then it should be present in the page links, if absent in the request then it should be absent in the page links. This covers both the conneg case and the case where `.ext` is explicity given.

Likewise &_format (though I rarely use that param) should follow the requestURI.

Also, the response should carry a Content-Location header that *does* have the .ext or &_format that gets you back the same rendering of the page - but I think the core of elda already handles generating Content-Location headers (ie. I don't think its a concern of the renderer).. 

Hope that all make sense.

**Comment by ijdickinson** [comment] 2015-02-10 17:45
Understood, but the problem is that this:

> There are two categories of URI, those arising from 'data' triples returned from the SPARQL view 
> query and those injected by elda and/or the render for linking pages. In the case of URI in the 
> data, modulo staging rewrites, they should be as present in the data (usually without 
> suffices) - regardless of conneg or &_format or trailing .format.

directly contradicts an earlier requested feature (unfortunately not in the tracker, or I'd link to it).  It's probably less important now that we're using Velocity HTML as the default renderer, but I just want to be clear that if we implement this behaviour, we're negating an explicitly requested feature. 

From my point of view, it would be easier: at the moment, I have to decide when to add the `.html` extension. If the answer is 'never', that actually simplifies the code and we can close #106 trivially.

**Comment by skwlilac** [comment] 2015-02-10 18:56
Hmmm.. hard to evaluate "directly contradicts" without the detail of what that feature request was or where it originated.

What I've described and I guess implictly asked for is the same behaviour as the built-in JSON, RDF, TTL, XML and XSLT driven HTML renderers do. c.f. the page navigation and data links on (say):

 `http://environment.data.gov.uk/doc/bathing-water`
 `http://environment.data.gov.uk/doc/bathing-water.html`
 `http://environment.data.gov.uk/doc/bathing-water.json`

They 'key' any URI that they 'inject' on the page from the URI for the page being displayed. In the case of the XML and XSLT driven HTML renders that is carried on the /result@href attribute at the root of the XML formatted response. In the case of an RDF format its carried as the subject of an `rdf:type api:Page` statement (AFAICT) - but the XML, JSON and RDF renderers don't add the 'navifhation' in the way that the HTML renders do.

**Comment by ijdickinson** [comment] 2015-02-10 21:01
> hard to evaluate "directly contradicts" without the detail of what that feature request was 
> or where it originated.

I heard the same request from Dave, Brian, and, er, you.  The problem at the time was: suppose you configure xhtml as the default renderer, and vhtml as an alternative html renderer. View a page `something.vhtml`. Click on a link to a resource in the same dataset, you see a page for that resource but presented in the default html renderer - i.e. xhtml. It makes for a jarring user experience, because every time you follow a link you have to take two actions: select the resource, and then select the non-default rendering.

The feature request was: if an explicit rendering is requested by the user (i.e. which sets `_suffix` in the Elda `bindings` object passed to the renderer factory), the link hrefs should have the appropriate suffix so that you remain within the same rendered presentation. Issue  #106 was an addendum to that original request, in which if the current renderer happens to be the default rendering, it's not necessary to explicitly set the format via the href suffix. As noted earlier, having looked at #106, I'm not sure it's currently possible without more info being passed through the renderer factory API.

**Comment by skwlilac** [comment] 2015-02-10 22:54
I suspect there may be subtle differences the requests made or in their expression.

When the default renderer is selected by virtue of being default, that can only happen through conneg when neither `.format` or `&_format` are present in the request. In the other cases the default render is selected on the basis of either `.format` or `&_format`. Personnally, I'd happy if the velocity render follows the same behaviour as the other renderers for any URI that *it* adds to the rendered response - which is, AFAICT, to preserve any `.format` or `&_format` in the request. For items of response data (as opposed to response page metadata) I'd expect the links (as is the case in there other renderers) to be presented as they appear in the data (i.e. that they do not get extended with `.format` in any circumstance - not least because some of those link targets may be to a different site).

It's not clear to me whether Dave's request in #106 is really about renderings made with renderer that happens to be default, however selected, or about request made without a `.format`. I don't know/recall what Brian's request was.

**Comment by ijdickinson** [comment] 2015-02-10 23:12
I've pushed a branch `issue-106` which disables suffix manipulation altogether. Let's try it and see if that causes fewer problems than it solves!

**Comment by skwlilac** [comment] 2015-02-11 10:51
Brilliant... the `issue-106` branch is doing exactly as I'd expect. I suspect it will address the issue Dave raised as #106. Thanks

**Comment by ijdickinson** [comment] 2015-09-11 11:18
I think this issue is closed now.

**Closed by ijdickinson** 2015-09-11 11:18 UTC
