### ISSUE TITLE
Incorrect placing of map tiles possibly due to repeating same map tile

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/elda#111] opened 2014-12-28 18:07 UTC
I noticed this and am recording in passing.  Its not an immediate problem for me.

I have an elda page displaying the same location in multiple nested places in a view.  I have a community resource which is related to a subcommunity resource.  The subcommunity resource refers back to its parent resource.  The map tile for the community resource is thus displayed both at the top level and two levels deeper.

I have attached  screen shot of the resulting elda display showing the map tiles placed incorrectly.

![screenshot from 2014-12-28 17 56 58](https://cloud.githubusercontent.com/assets/3245172/5564487/9e248de8-8ebb-11e4-9866-f6910d762617.png)

I'll attach a gist for the html in a mo'

**Comment by ijdickinson** [comment] 2015-01-05 09:26
Thanks. This will be much easier to debug if you can supply a minimal runnable example.

**Comment by ijdickinson** [comment] 2015-01-05 10:26
I have a theory about what might be going wrong here, but it would still be useful to have a MRE so that I can verify the fix.

**Comment by bwm-epimorphics** [comment] 2015-01-05 10:57
Ok.  I'm wondering what form an MRE would take.  

You will presumably need a config and test data.  If I download the Elda repo, are there tests in there that would give me a pattern to follow.  Then I could try to create a test case that would be minimal work for you.

**Comment by ijdickinson** [comment] 2015-01-05 11:11
Just config and test data should be fine, thanks. Once I figure out what the problem is, I'll create a regression test from it.

**Comment by bwm-epimorphics** [comment] 2015-01-05 12:32
I've put config and data at https://gist.github.com/bwm-epimorphics/618b1bce1e3266595bd9

**Comment by ijdickinson** [comment] 2015-01-08 10:21
I've merged the `issue-111` branch into master. Can we close this issue now?

**Closed** 2015-01-08 10:32 UTC
Labels: bug
