### ISSUE TITLE
Setting velocity property velocimacro.max.depth=50 fails if there whitespace after the 0

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/elda#110] opened 2014-12-28 17:53 UTC
If there is a space after the '50' then get a number format exception "50 ".

**Comment by ijdickinson** [comment] 2015-01-05 10:21
I confirm that this problem occurs, but it's not an Elda bug. The relevant stacktrace is:

    root cause
    java.lang.NumberFormatException: For input string: "50 "
	java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	java.lang.Integer.parseInt(Integer.java:492)
	java.lang.Integer.<init>(Integer.java:677)
	org.apache.commons.collections.ExtendedProperties.getInteger(ExtendedProperties.java:1441)
	org.apache.commons.collections.ExtendedProperties.getInteger(ExtendedProperties.java:1394)
	org.apache.commons.collections.ExtendedProperties.getInt(ExtendedProperties.java:1366)
	org.apache.velocity.runtime.RuntimeInstance.getInt(RuntimeInstance.java:1798)
	org.apache.velocity.runtime.directive.VelocimacroProxy.init(VelocimacroProxy.java:266)
	org.apache.velocity.runtime.VelocimacroManager$MacroEntry.<init>(VelocimacroManager.java:471)
	org.apache.velocity.runtime.VelocimacroManager$MacroEntry.<init>(VelocimacroManager.java:448)
	org.apache.velocity.runtime.VelocimacroManager.addVM(VelocimacroManager.java:108)
	org.apache.velocity.runtime.VelocimacroFactory.addVelocimacro(VelocimacroFactory.java:463)
	org.apache.velocity.runtime.RuntimeInstance.addVelocimacro(RuntimeInstance.java:1741)
	org.apache.velocity.runtime.directive.Macro.init(Macro.java:115)
	org.apache.velocity.runtime.parser.node.ASTDirective.init(ASTDirective.java:126)
	org.apache.velocity.runtime.parser.node.SimpleNode.init(SimpleNode.java:309)
	org.apache.velocity.Template.initDocument(Template.java:227)
	org.apache.velocity.Template.process(Template.java:135)
	org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:437)
	org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	org.apache.velocity.runtime.directive.Parse.render(Parse.java:197)
	org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	org.apache.velocity.Template.merge(Template.java:356)
	org.apache.velocity.Template.merge(Template.java:260)

That's (a) not in the Elda code, and (b) gives a pretty clear diagnostic of what the problem is. One could argue that trailing spaces in the `velocity.properties` file should not be regarded as significant, but that's a discussion to have upstream with the Velocity team.

Given that, at present, "50 " is illegal input as far as Velocity is concerned, and that there's nothing I can easily do to change that in the Elda code, I'm closing this as an Elda bugrep

**Closed by ijdickinson** 2015-01-05 10:21 UTC
Labels: bug

**Comment by bwm-epimorphics** [comment] 2015-01-05 10:49
I hadn't realised the velocity properties file was passed directly to Velocity to process.  Agree wontfix is the right response.
