### ISSUE TITLE
Rendering of repeated resources in list view using VHTML renderer.

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/elda#112] opened 2014-12-28 18:30 UTC
I have a resource TestCommunity.  It is related to a sub-community with the property dcterms:hasPart.  The sub-community is related to its parent community with the property dcterms:isPartOf.

I have a view that displays a community including the labels, but no other properties, of its parent communities and child communities.  This displays correctly when displaying a single community,e g.

![image](https://cloud.githubusercontent.com/assets/3245172/5564546/07529348-8ebf-11e4-8e73-ed802a23ef76.png)

However, when displayed in a list view the views of the parent and child properties are expanded recursively, e.g.

![image](https://cloud.githubusercontent.com/assets/3245172/5564548/63f3f0f6-8ebf-11e4-96d3-8e75bc324bc6.png)

If I have several levels of nesting this could get rather messy.

**Comment by ijdickinson** [comment] 2015-01-05 09:21
The new renderer code contains a check that ensures that no recursive loops are constructed in the output. If a resource appears that already appears on the path back to the root node, it is shown in abbreviated form.

What I suspect is happening here is an interaction with another feature: eliding previously displayed resources is *not* done if that resource's property is explicitly named in the view. This was actually implemented per a request from you :)

What I'll need in order to investigate this, and determine what fixes we can apply to mitigate display artifacts while maintaining the design goals, is a complete minimal test case.

**Comment by bwm-epimorphics** [comment] 2015-01-05 14:24
Following the same style as for issue 111 I've created a test case based on almost identical config and data.  The GIST is at https://gist.github.com/bwm-epimorphics/7473edf86a3ae8f4fd1c.

To see the issue, visit /id/community

**Comment by ijdickinson** [comment] 2015-01-06 16:55
This is not a bug showing "recursive" inclusions - if it were, the sub-community would link to the parent which would link to the child etc etc. The Java code that unrolls the RDF graph into a DisplayHierarchy checks for such loops, and breaks them at the first occurrence of a resource node on its own path to the roots of the hierarchy (unless that node is explicitly included in the Elda view description).

The problem here, as I see it, is that terminal nodes which are loops back to an earlier point in the display hierarchy are not clearly distinguished from other, normal, nodes. This can make the display more confusing, as you observed. So what I've done to improve this is:

* added CSS classes to denote leaf nodes and loop nodes, so that they can be styled differently if required
* break out the code that displays looped nodes into a separate Velocity macro, so that the default behaviour can be changed on a per-installation basis if required
* changed the default behaviour so that a loop node only displays its label and URI, and a visual marker to indicate that this is a re-occurrence of a node that has already been displayed.

The code is currently in the issue-112 branch if you want to try it out.

**Comment by bwm-epimorphics** [comment] 2015-01-06 21:00
I was chatting with Stuart and Chris who explained that my expectations of what the renderer would do is incorrect.

As a user, when I define a view in the api config, say:

  "label, description, hasPart.label"

I was expecting that view definition to influence/control the shape of the html generated by the html renderer, i.e. the html would show a label or the object of the hasPart property, but not a description (because there is no hasPart.description in the view definition), even if the model being rendered has a description for that resource.

Stuart and Chris explained that is not what Elda does.  The view defines the data that is rendered but does not directly influence the shape of the html that is rendered.  A view only controls the data to be rendered, not how it is rendered.  At least that is the case for the XSLT html renderer.

So given that the velocity renderer is not intended to follow the view definition when laying out the html, then I agree its not a bug in the code.  I have modified the title of the issue to try to reflect that.

Given that limitation, the changes you have described seem sensible and I will try them out.

**Comment by bwm-epimorphics** [comment] 2015-01-07 15:28
What I was expecting was that the html display would show the properties as specified in the view specification.  I understand now that is not what Elda does.

**Comment by ijdickinson** [comment] 2015-01-08 10:21
I've merged the `issue-112` branch into master. Can we close this issue now?

**Closed** 2015-01-08 10:32 UTC
Labels: enhancement
